# Generated by Django 3.0.6 on 2020-09-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('sousol', models.CharField(max_length=500)),
                ('entresol', models.CharField(max_length=500)),
                ('premier_etage', models.CharField(max_length=500)),
                ('troisieme_etage', models.CharField(max_length=500)),
                ('quatrieme_etage', models.CharField(max_length=500)),
            ],
        ),
    ]
