# Generated by Django 3.0.6 on 2020-10-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stLeon', '0008_auto_20201004_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batiments',
        ),
    ]
